"""Render slide mockups — Luminous Signal design philosophy.

Final pass: commanding typography, precise spatial rhythm, museum-grade polish.
"""

from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

W, H = 1920, 1080
M = 96  # margin

# --- Palette ---
BG         = (18, 18, 30)
SURFACE    = (30, 31, 48)
RULE       = (50, 52, 72)
WHITE      = (255, 255, 255)
PRI        = (240, 242, 250)
SEC        = (160, 165, 190)
TER        = (100, 105, 130)
EMERALD    = (72, 199, 142)
ELECTRIC   = (100, 140, 255)
G1, G2     = (70, 95, 210), (120, 155, 255)
AMBER      = (255, 183, 77)
CORAL      = (239, 108, 108)

# --- Fonts ---
FD = Path(r"C:\Claude Code\.claude\skills\canvas-design\canvas-fonts")
def _f(n, s):
    try: return ImageFont.truetype(str(FD / n), s)
    except: return ImageFont.load_default()

# Display — Outfit Bold (scaled up dramatically)
D140 = _f("Outfit-Bold.ttf", 140)
D96  = _f("Outfit-Bold.ttf", 96)
D64  = _f("Outfit-Bold.ttf", 64)
D48  = _f("Outfit-Bold.ttf", 48)
D36  = _f("Outfit-Bold.ttf", 36)
D28  = _f("Outfit-Bold.ttf", 28)

# Body — InstrumentSans
B26  = _f("InstrumentSans-Regular.ttf", 26)
B26B = _f("InstrumentSans-Bold.ttf", 26)
B22  = _f("InstrumentSans-Regular.ttf", 22)
B22B = _f("InstrumentSans-Bold.ttf", 22)

# Numbers — GeistMono
N64  = _f("GeistMono-Bold.ttf", 64)
N36  = _f("GeistMono-Bold.ttf", 36)
N22  = _f("GeistMono-Regular.ttf", 22)
N22B = _f("GeistMono-Bold.ttf", 22)

# Labels — WorkSans
L18  = _f("WorkSans-Bold.ttf", 18)
L22  = _f("WorkSans-Bold.ttf", 22)
L14  = _f("WorkSans-Bold.ttf", 14)

# --- Helpers ---
def _c():
    i = Image.new("RGB", (W, H), BG); return i, ImageDraw.Draw(i)
def _rr(d, xy, f, r=8): d.rounded_rectangle(xy, radius=r, fill=f)
def _ac(d, x, y, w, c, t=3): d.rectangle([x, y, x+w, y+t], fill=c)
def _gr(i, d, x, y, w, h, c1, c2):
    s = max(1, w//200)
    for j in range(0, w, s):
        t = j/max(1,w-1)
        d.rectangle([x+j, y, x+min(j+s,w), y+h],
                     fill=tuple(int(c1[k]+(c2[k]-c1[k])*t) for k in range(3)))
def _fd(d, ys, h, cf, ct):
    for i in range(h):
        t = i/max(1,h-1)
        d.rectangle([0, ys+i, W, ys+i+1],
                     fill=tuple(int(cf[k]+(ct[k]-cf[k])*t) for k in range(3)))
def _ci(d, cx, cy, r, f): d.ellipse([cx-r, cy-r, cx+r, cy+r], fill=f)
def _tw(d, t, f): bb=d.textbbox((0,0),t,font=f); return bb[2]-bb[0]
def _tc(d, cx, cy, t, f, c=WHITE):
    bb=d.textbbox((0,0),t,font=f)
    d.text((cx-(bb[2]-bb[0])//2, cy-(bb[3]-bb[1])//2-2), t, fill=c, font=f)
def _w(d, x, y, w, t, f, c, lh=32):
    words, lines, cur = t.split(), [], []
    for word in words:
        test = " ".join(cur+[word])
        if d.textbbox((0,0), test, font=f)[2] <= w: cur.append(word)
        else:
            if cur: lines.append(" ".join(cur))
            cur = [word]
    if cur: lines.append(" ".join(cur))
    for i, ln in enumerate(lines): d.text((x, y+i*lh), ln, fill=c, font=f)
    return len(lines)


# ═══════════════════════════════════════════════════════════════════
# SLIDE 1: TITLE
# ═══════════════════════════════════════════════════════════════════

def slide_title():
    img, d = _c()

    # Full-page gradient band — covers upper 60%
    bh = 640
    _gr(img, d, 0, 0, W, bh, G1, G2)
    _fd(d, bh, 100, G2, BG)

    # --- Centered title block ---
    # Measure text widths for centering
    t1 = "YOUTUBE"
    t2 = "ANALYTICS"
    t3 = "MONTHLY PERFORMANCE REPORT"
    w1 = _tw(d, t1, D140)
    w2 = _tw(d, t2, D140)
    w3 = _tw(d, t3, D48)

    # Vertical center: title block is ~380px tall, center it in the slide
    block_h = 160 + 160 + 80 + 20  # line1 + line2 + subtitle + accent
    block_top = (H - block_h) // 2 - 40  # shift slightly above true center

    # Line 1: YOUTUBE
    d.text(((W - w1) // 2, block_top), t1, fill=WHITE, font=D140)

    # Line 2: ANALYTICS
    d.text(((W - w2) // 2, block_top + 160), t2, fill=WHITE, font=D140)

    # Emerald accent bar — centered, 120px wide
    bar_w = 120
    d.rectangle([(W - bar_w) // 2, block_top + 340,
                 (W + bar_w) // 2, block_top + 346], fill=EMERALD)

    # Subtitle
    d.text(((W - w3) // 2, block_top + 370), t3, fill=(210, 218, 255), font=D48)

    # Date — centered below subtitle
    date_t = "February 2026"
    dw = _tw(d, date_t, B26)
    d.text(((W - dw) // 2, block_top + 440), date_t, fill=SEC, font=B26)

    # Footer — bottom left
    d.text((M, H-66), "GENERATED BY", fill=TER, font=L14)
    d.text((M+130, H-68), "YouTube Analytics Engine", fill=SEC, font=B22)

    return img


# ═══════════════════════════════════════════════════════════════════
# SLIDE 2/3: CHANNEL DATA
# ═══════════════════════════════════════════════════════════════════

def slide_channel(name="Michele Torti", label="YOUR CHANNEL", comp=False,
                  subs="30,700", views="92,757", vids="19", eng="3.83%",
                  top_videos=None):
    img, d = _c()
    if top_videos is None:
        top_videos = [
            ("Master 80% of Antigravity in 25 minutes (You'll be...)", "34,857", "3.74%"),
            ("Stop Building n8n AI Agent (Claude Code Does It IN...)", "19,080", "3.53%"),
            ("Turn ALL Your Workflows into Custom Apps (Antigrav...)", "13,698", "3.39%"),
            ("The BEST Loom Outreach Strategy for your AI Agency...", "3,052", "2.10%"),
            ("Build ANY App with Google's Antigravity + n8n (It'...", "2,463", "1.80%"),
        ]
    ac = ELECTRIC if comp else EMERALD

    # Gradient header
    _gr(img, d, 0, 0, W, 72, G1, G2)
    _fd(d, 72, 24, G2, BG)

    # Label
    d.text((M, 96), label, fill=ac, font=L22)

    # Channel name — large and commanding
    d.text((M, 126), name, fill=PRI, font=D64)

    # Accent line
    d.rectangle([M, 204, W-M, 207], fill=ac)

    # 4 metric cards
    cw = (W - 2*M - 3*16)//4
    ch = 110
    cy = 228
    metrics = [("SUBSCRIBERS",subs,EMERALD),("VIEWS (60D)",views,ELECTRIC),
               ("VIDEOS",vids,AMBER),("ENGAGEMENT",eng,CORAL)]
    for i,(ml,mv,mc) in enumerate(metrics):
        cx = M + i*(cw+16)
        _rr(d, [cx, cy, cx+cw, cy+ch], SURFACE)
        _ac(d, cx, cy, cw, mc)
        d.text((cx+24, cy+14), ml, fill=TER, font=L18)
        d.text((cx+24, cy+46), mv, fill=PRI, font=N64)

    # TOP PERFORMING VIDEOS
    sy = cy + ch + 28
    d.text((M, sy), "TOP PERFORMING VIDEOS", fill=ac, font=L22)

    # Column headers
    hy = sy + 38
    d.text((M+60, hy), "TITLE", fill=TER, font=L14)
    d.text((W-M-340, hy), "VIEWS", fill=TER, font=L14)
    d.text((W-M-140, hy), "ENGAGEMENT", fill=TER, font=L14)
    d.rectangle([M, hy+24, W-M, hy+25], fill=RULE)

    # Rows
    rh = 64
    rs = hy + 36
    for i,(title,vv,ve) in enumerate(top_videos):
        ry = rs + i*(rh+6)
        _rr(d, [M, ry, W-M, ry+rh], SURFACE if i%2==0 else BG, r=4)
        d.text((M+20, ry+18), f"{i+1}.", fill=TER, font=B22B)
        d.text((M+60, ry+18), title, fill=PRI, font=B22)
        d.text((W-M-340, ry+18), vv, fill=EMERALD, font=N22B)
        d.text((W-M-120, ry+18), ve, fill=SEC, font=N22)

    return img


# ═══════════════════════════════════════════════════════════════════
# SLIDE 4: COMPARATIVE ANALYSIS
# ═══════════════════════════════════════════════════════════════════

def slide_comparative():
    img, d = _c()

    # Header — large and clear
    d.text((M, 32), "COMPARATIVE", fill=PRI, font=D64)
    d.text((M, 104), "ANALYSIS", fill=PRI, font=D64)
    d.rectangle([M, 180, M+160, 184], fill=ELECTRIC)

    # Overview card
    oy = 204
    oh = 130
    _rr(d, [M, oy, W-M, oy+oh], SURFACE)
    _ac(d, M, oy, W-2*M, ELECTRIC)
    overview = ("While Michele maintains high publishing frequency and solid engagement, "
                "competitors achieve 8-10x higher average views through strategic content "
                "selection and broader topical reach. Competitors focus heavily on trending "
                "tool comparisons and business applications.")
    _w(d, M+28, oy+22, W-2*M-56, overview, B22, SEC, lh=32)

    # Two columns
    gap = 20
    cw = (W-2*M-gap)//2
    cy = oy + oh + 20
    ch = 400

    # Key Trends
    lx = M
    _rr(d, [lx, cy, lx+cw, cy+ch], SURFACE)
    _ac(d, lx, cy, cw, EMERALD)
    d.text((lx+28, cy+22), "KEY TRENDS", fill=EMERALD, font=L22)
    trends = [
        "AI/Antigravity tool comparison content generates massive outlier views (10x+ average)",
        "\"Master X% in Y minutes\" title format consistently drives 70k+ views across the niche",
        "Claude Code vs competitor debates are among the highest-searched topics in the space",
    ]
    for i,t in enumerate(trends):
        ty = cy+72 + i*104
        _ci(d, lx+44, ty+14, 6, EMERALD)
        _w(d, lx+66, ty, cw-94, t, B22, SEC, lh=30)

    # Content Gaps
    rx = M + cw + gap
    _rr(d, [rx, cy, rx+cw, cy+ch], SURFACE)
    _ac(d, rx, cy, cw, AMBER)
    d.text((rx+28, cy+22), "CONTENT GAPS", fill=AMBER, font=L22)
    gaps = [
        "Comparative analysis videos (ClawdBot vs Claude Code) are entirely missing from the channel",
        "AI experimentation and focused reasoning model reviews are an untapped content format",
        "Monetization-focused tutorials (making money with AI tools) are underserved in the niche",
    ]
    for i,g in enumerate(gaps):
        gy = cy+72 + i*104
        _ci(d, rx+44, gy+14, 6, AMBER)
        _w(d, rx+66, gy, cw-94, g, B22, SEC, lh=30)

    # Top Performer
    tpy = cy + ch + 20
    tph = 68
    _rr(d, [M, tpy, W-M, tpy+tph], SURFACE)
    d.text((M+28, tpy+22), "TOP PERFORMER", fill=EMERALD, font=L22)
    d.text((M+260, tpy+16), "Jack Roberts", fill=PRI, font=D36)
    d.text((W-M-440, tpy+24), "707,437 views", fill=SEC, font=N22)
    d.text((W-M-190, tpy+24), "3.62% eng", fill=SEC, font=N22)

    return img


# ═══════════════════════════════════════════════════════════════════
# SLIDE 5: VIDEO IDEA
# ═══════════════════════════════════════════════════════════════════

def slide_idea():
    img, d = _c()

    # Number circle + label
    _ci(d, M+36, 60, 36, EMERALD)
    _tc(d, M+36, 60, "1", D28, WHITE)
    d.text((M+88, 38), "VIDEO IDEA", fill=TER, font=L22)

    # Title — commanding
    d.text((M, 120), "ClawdBot vs Claude Code:", fill=PRI, font=D48)
    d.text((M, 180), "I Tested Both for 50 Hours", fill=PRI, font=D48)
    d.text((M, 240), "(Honest Results)", fill=SEC, font=D36)

    # Accent
    d.rectangle([M, 296, M+80, 300], fill=EMERALD)

    # Two columns
    gap = 20
    cw = (W-2*M-gap)//2
    cy = 320
    ch = 480

    # Title Variations
    lx = M
    _rr(d, [lx, cy, lx+cw, cy+ch], SURFACE)
    _ac(d, lx, cy, cw, CORAL)
    d.text((lx+28, cy+22), "TITLE VARIATIONS", fill=CORAL, font=L22)
    titles = [
        "ClawdBot vs Claude Code: I Tested Both for 50 Hours.",
        "How to Compare ClawdBot and Claude Code — A Real Test.",
        "The Truth About AI Coding: ClawdBot vs Claude Code.",
        "Why ClawdBot and Claude Code Aren't What You Think.",
        "50 Hours Testing ClawdBot vs Claude Code — Real Results.",
    ]
    for i,t in enumerate(titles):
        ty = cy+66 + i*80
        d.text((lx+28, ty), f"{i+1}.", fill=TER, font=B22B)
        _w(d, lx+64, ty, cw-92, t, B22, SEC, lh=28)

    # Hook Options
    rx = M + cw + gap
    _rr(d, [rx, cy, rx+cw, cy+ch], SURFACE)
    _ac(d, rx, cy, cw, ELECTRIC)
    d.text((rx+28, cy+22), "HOOK OPTIONS", fill=ELECTRIC, font=L22)

    h1y = cy+66
    d.text((rx+28, h1y), "Hook 1", fill=EMERALD, font=B22B)
    _w(d, rx+28, h1y+34, cw-56,
       "\"I spent 50 hours testing ClawdBot against Claude Code on real projects. "
       "What I found completely changed how I think about AI coding assistants. "
       "Stay with me — this changes everything.\"",
       B22, SEC, lh=30)

    h2y = cy+270
    d.text((rx+28, h2y), "Hook 2", fill=EMERALD, font=B22B)
    _w(d, rx+28, h2y+34, cw-56,
       "\"Everyone says Claude Code is the best AI coding tool. But after testing "
       "ClawdBot head-to-head for 50 hours, I'm not so sure. Here are my honest results.\"",
       B22, SEC, lh=30)

    # Badge
    by = cy + ch + 16
    _rr(d, [M, by, M+240, by+48], (30,80,60), r=24)
    d.text((M+24, by+12), "HIGH POTENTIAL", fill=EMERALD, font=L22)

    # Topic
    d.text((M, by+64),
           "Topic: AI coding assistant comparison with real-world testing",
           fill=TER, font=B22)

    return img


# ═══════════════════════════════════════════════════════════════════
# SLIDE 6: TAKEAWAYS
# ═══════════════════════════════════════════════════════════════════

def slide_takeaways():
    img, d = _c()

    # Gradient band
    bh = 160
    _gr(img, d, 0, 0, W, bh, G1, G2)
    _fd(d, bh, 60, G2, BG)

    # Header — two-line treatment for presence
    d.text((M, 32), "KEY TAKEAWAYS", fill=WHITE, font=D64)
    d.text((M, 100), "& NEXT STEPS", fill=(200,210,255), font=D36)

    # 3 takeaway cards
    takeaways = [
        "Reduce publishing frequency but focus on high-impact trending topics like ClawdBot vs Claude Code comparisons that generate 10x+ outlier views.",
        "Adopt the proven 'Master X% in Y minutes' title format that consistently generates 70k+ views across competitors — adapt it to your Antigravity and n8n content.",
        "Bridge technical expertise with business applications — create monetization case studies using Antigravity and n8n to capture the underserved 'making money with AI' audience.",
    ]
    for i,text in enumerate(takeaways):
        iy = 268 + i*198
        # Card
        _rr(d, [M+96, iy-4, W-M, iy+140], SURFACE)
        # Circle
        _ci(d, M+48, iy+60, 40, EMERALD)
        _tc(d, M+48, iy+60, str(i+1), D28, WHITE)
        # Text
        _w(d, M+124, iy+24, W-2*M-156, text, B26, PRI, lh=38)

    # Footer
    ft = "Review monthly to track progress and adjust strategy"
    fw = _tw(d, ft, B22)
    d.text(((W-fw)//2, H-56), ft, fill=TER, font=B22)

    return img


# ═══════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    out = Path(r"C:\Claude Code\YouTube Competitor Analysis\slide_mockups")
    out.mkdir(exist_ok=True)
    slides = [
        ("01_title.png", slide_title),
        ("02_your_channel.png", lambda: slide_channel(
            "Michele Torti","YOUR CHANNEL",False,"30,700","92,757","19","3.83%")),
        ("03_competitor.png", lambda: slide_channel(
            "Jack Roberts","COMPETITOR",True,"112,000","707,437","13","3.62%",
            [("NotebookLM just got 10X better (AntiGravity)","135,488","3.56%"),
             ("Antigravity Skills are a Cheat Code (NEW System)","101,386","3.57%"),
             ("AntiGravity just became UNSTOPPABLE (OpenCode)","94,774","3.60%"),
             ("How I vibecode Beautiful $10,000 AI Websites (Anti...","91,514","3.20%"),
             ("Master 95% of Antigravity in 28 Mins (Unlock Super...","73,126","3.10%")])),
        ("04_comparative.png", slide_comparative),
        ("05_video_idea.png", slide_idea),
        ("06_takeaways.png", slide_takeaways),
    ]
    for fn, render in slides:
        render().save(str(out/fn), "PNG")
        print(f"  {fn}")
    print(f"\nDone — {len(slides)} slides")
